### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#155]
I try to follow your newest [installation documentation](https://github.com/metabrainz/musicbrainz-docker/blob/master/README.md).

If I try to build the Docker Images with 
`sudo docker-compose build`
I get the error:
```
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/
```

What exactly do I have to install in addition to the steps in the [linked Docker instructions](https://docs.docker.com/compose/install/):
a) `sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`
and
b) `sudo chmod +x /usr/local/bin/docker-compose`

The command 
`ubuntu@ubuntu:~/musicbrainz-docker$ docker-compose --version`
returns:
`docker-compose version 1.25.5, build 8a1c60f6`

The also mentioned "symbolic link" and "Command-line completion" doesn't help.

(System: fresh installed Ubuntu v20.04 in VM, with all available updates up-to-date)

**Comment by yvanzo** [comment]
The Docker daemon needs to be installed and started indeed. It is listed in [prerequisites to install Docker Compose](https://docs.docker.com/compose/install/#prerequisites) on Linux. Following this link, there are [instructions to install Docker Engine on Ubuntu](https://download.docker.com/linux/ubuntu). Even though OS requirements are slightly outdated (Ubuntu 20.04 is supported already) there is a section “[Install using the repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)”.

But, since your version of Ubuntu is recent, it also comes with a recent version of Docker and Docker Compose, so you can just install it from the Ubuntu repositories:

```bash
sudo rm -vf /usr/local/bin/docker-compose
sudo apt-get install docker.io docker-compose docker-doc
```

Then follow “[Post-installation steps for Linux](https://docs.docker.com/engine/install/linux-postinstall/)” or directly start the Docker daemon with:

```bash
sudo systemctl start docker.service
```

To make it start on system startup:

```bash
sudo systemctl enable docker.service
```

**Comment by PeterCodar** [comment]
Thank you @yvanzo that works fine.

Maybe you could add the line
`sudo apt-get install docker.io docker-compose docker-doc`
to "_Required Software_" in the instructions, something like

Required software
**Docker Engine and** Docker Compose 1.21.1 (or higher), see how to install Docker Compose
`sudo apt-get install docker.io docker-compose docker-doc`

**Comment by SuperSandro2000** [comment]
Just keep in mind that docker.io is not the docker-ce package and docker developer do not offer support for docker.io.

**Comment by PeterCodar** [comment]
For those (like me) not knowing the difference between docker.io and docker-ce:
https://stackoverflow.com/questions/45023363/what-is-docker-io-in-relation-to-docker-ce-and-docker-ee

**Comment by yvanzo** [comment]
Adding instructions specifically for Ubuntu with pull request <https://github.com/metabrainz/musicbrainz-docker/pull/160>.
