### ISSUE TITLE
unmatched md5 checksum

### ISSUE THREAD

**Issue by marstall** [metabrainz/musicbrainz-docker#189]
on a clean checkout, following the instructions, after running the following step:

```
sudo docker-compose run --rm musicbrainz createdb.sh -fetch
```

I get

```
/usr/local/bin/fetch-dump.sh: unmatched MD5 checksum: a29591768a7ccbcb85f42e352a4038a1 *mbdump-wikidocs.tar.bz2 *mbdump-wikidocs.tar.bz2
ERROR: 70
```

Thanks for any support!

**Comment by marstall** [comment]
oh also i am running this on M1!

**Comment by yvanzo** [comment]
Possibly the download of `mbdump-wikidocs.tar.bz2` failed due to network issue. Did you try running once again? I just tested the current checksum which match the current `mbdump-wikidocs.tar.bz2` at least. Please reopen this issue if it fails again.

(This project uses Docker image with OS Linux for architecture amd64, so it runs in macOS on M1 likely through Rosetta 2.)
