### ISSUE TITLE
After full dump import: Reindex only the few not yet indexed entries?

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#199]
After the download of the newest full dump data and search indexes (20210529-001720), I see the following check result:

```
@ubuntu:~/musicbrainz-docker$ admin/check-search-indexes all
CORE           STATUS  INDEX     DB
editor         OK      0         /0
instrument     OK      1007      /1007
series         --      13362     /13346
place          --      47396     /47388
event          --      51549     /51512
tag            --      97814     /108468
area           OK      118525    /118525
label          --      202686    /202656
cdstub         --      289456    /289460
annotation     --      460633    /424625
work           --      1507317   /1506968
artist         --      1828570   /1828207
release-group  --      2276463   /2275944
release        --      2890692   /2889928
url            --      7787727   /7785391
recording      --      24871477  /24865197
@ubuntu:~/musicbrainz-docker$ 

```

How can I reindex only the few not yet indexed entries to get an **OK** for identical numbers on every row?

**Comment by yvanzo** [comment]
Sorry for the late answer.

First, the output `check-search-indexes` is making sense only when the replication is turned off, because the search indexer needs some time to catch up with changes replicated to the database.

Second, the indexer is not able to check for obsolete or missing index entries, it is only able to rebuild a search index (CORE).

For example, to rebuild the search index for series which has 16 obsolete entries in your example, you can run the following commands to delete all the entries of this index and then to rebuild it:
```bash
index=series
admin/delete-search-indexes "$index"
sudo docker-compose exec indexer python -m sir reindex --entity-type "$index"
```

To rebuild all the above not OK search indexes in one command:


```bash
for index in series place event tag label cdstub annotation work artist release-group release url recording
do
  admin/delete-search-indexes "$index"
  sudo docker-compose exec indexer python -m sir reindex --entity-type "$index"
done
```
