### ISSUE TITLE
ip:8080 to reach search API redirects me to https://musicbrainz.org/search

### ISSUE THREAD

**Issue by bahoh** [metabrainz/musicbrainz-docker#91]
Hi,

I followed all the steps for installing musicbrainz server. I see two docker containers running. musicbrainz-docker_musicbrainz and musicbrainz-docker_search, at 5000 and 8080 port respectively. However, if I go to my local IP address with 8080 port, it soon redirects me to https://musicbrainz.org/search page. Do you know how to turn off the redirection?

Thanks,

**Comment by yvanzo** [comment]
Hi! There is no way to turn it off. The search server doesn't have any web user interface, thus it is expected to redirect to a search page. Ideally, it should redirect to `https://<server name>/search` but it has been primarily built for musicbrainz.org. This won't be changed for the current search server because it is going to be replaced very soon (working on it).

**Comment by phirestalker** [comment]
Ya, months later, so is there a way for US to enable the local search server in the docker image? There used to be a process with the old VM for redirecting to the local instance.

Also, am I crazy? What exactly is the 12 hours of indexing for if not the local search instance? Am I to believe that is all wasted time?

**Comment by yvanzo** [comment]
@phirestalker, the local search server has always been and it is still enabled, see https://github.com/metabrainz/musicbrainz-docker/blob/21c9b4f6f307c0152572142960454d1f5245f9f2/musicbrainz-dockerfile/DBDefs.pm#L166

It can be accessed through your website, e.g. https://localhost:5000/search
