### ISSUE TITLE
Docker image for oracle jdk no longer available

### ISSUE THREAD

**Issue by dns53** [metabrainz/musicbrainz-docker#93]
The JDK docker image that the indexer uses is no longer available in the docker hub repository.
You should switch to using openjdk docker images instead.

Modify indexer-dockerfile/Dockerfile and change the first line to use the latest openjdk java 8:
FROM openjdk:8-jdk

**Comment by yvanzo** [comment]
Hi, thank you for the notice!

It seems more conservative to use `airdock/oraclejdk:1.8` which replaces previous image since Jan, 20. Any reason not to keep using airdock image?

By the way, I’m currently working on [sir](https://github.com/metabrainz/sir/) as a replacement for the indexer.

Edit: just checked other/further docker images relying on Java: [`mb-solr`](https://github.com/metabrainz/mb-solr) uses OpenJDK.

**Comment by mayhem** [comment]
ListenBrainz is switching to this image as well, but we haven't really put anything to the test yet, but for cross-project consistency, let's do that until we learn otherwise.

**Comment by pingupingu** [comment]
I have created a pull request for this https://github.com/metabrainz/musicbrainz-docker/pull/94

**Comment by yvanzo** [comment]
Thanks, the corresponding commit for this issue has been applied onto master branch.
